version: '2'

services:
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - elastic_network

  python:
    build:
      context: .
      dockerfile: es.Dockerfile
    container_name: python
    ports:
      - 8888:8888
    networks:
      - elastic_network

volumes:
  elastic_data:
    driver: local

networks:
  elastic_network:
    driver: bridge
