version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - elastic_network

  python:
    build:
      context: .
      dockerfile: es.Dockerfile
    container_name: python
    depends_on:
      - elasticsearch    
    ports:
      - 8888:8888
    networks:
      - elastic_network

volumes:
  elastic_data:
    driver: local
    name: elastic_volume

networks:
  elastic_network:
    driver: bridge
    name: elastic_hub
